from typing import Protocol
from domain.events import NormalizedEvent


class PaymentProvider(Protocol):
    async def verify_webhook(self, raw_body: bytes, headers: dict[str, str]) -> bool: ...
    async def normalize_webhook(self, payload: dict) -> list[NormalizedEvent]: ...
    async def get_payment(self, payment_id: str) -> dict: ...
    async def get_order(self, order_id: str) -> dict: ...
    async def create_payment_link(self, request: dict) -> dict: ...
    async def get_payment_link(self, link_id: str) -> dict: ...
    async def cancel_payment_link(self, link_id: str) -> None: ...
    async def get_subscription(self, subscription_id: str) -> dict: ...
