export type CaseState='DETECTED'|'DIAGNOSING'|'ACTION_PROPOSED'|'POLICY_BLOCKED'|'AUTHORIZED'|'ACTION_EXECUTED'|'WAITING_FOR_OUTCOME'|'NEXT_ACTION_DUE'|'NEEDS_REVIEW'|'RECOVERED'|'FAILED'|'CLOSED';
export interface Overview {revenue_at_risk_minor:number;revenue_recovered_minor:number;recovery_rate:number;total_cases:number;open_cases:number;policy_blocks:number;human_escalations:number;trend:{date:string;risk:number;recovered:number}[];safety:{duplicate_actions_prevented:number;unauthorized_money_actions:number;disputed_customers_contacted:number}}
export interface RecoveryCase {id:string;customer_id:string|null;amount_minor:number;currency:string;case_type:string;state:CaseState;failure_category:string|null;payment_method?:string|null;recommended_action:string|null;recoverability:string|null;policy_status:string|null;created_at:string}
export interface PolicyCheck{name:string;result:'PASS'|'FAIL';detail?:string}
export interface Recommendation{recommended_action:string;reason_code:string;reason:string;confidence:number;recoverability:string;evidence_refs:string[];missing_data:string[];risk_flags:string[];fallback_action:string;requires_human_approval:boolean}
export interface PolicyDecision{allowed:boolean;action:string;reason_code:string;policy_version:string;resolution:string;checks:PolicyCheck[]}
export interface CaseDetail {case:Record<string,unknown>;diagnoses:Record<string,unknown>[];recommendations:Recommendation[];policy_decisions:PolicyDecision[];interventions:{action:string;status:string;provider_reference:string|null;created_at:string}[];outcome:{payment_id:string;recovered_amount_minor:number;attributed:boolean}|null;audit:{type:string;actor:string;before:string|null;after:string|null;at:string;data:Record<string,unknown>}[]}
export interface Degradation {alerts:{payment_method:string;ewma_success_rate:number;baseline_success_rate:number;z_score:number;status:string}[];sample_size:number;method:string}
export interface MerchantPolicy {financial?:{max_auto_action_amount_minor:number};attempts?:{max_recovery_actions_per_case:number;max_payment_links_per_case:number};escalation?:{confidence_below:number}}
export interface AuditRecord {id:string;case_id:string|null;trace_id:string|null;actor:string;event_type:string;before_state:string|null;after_state:string|null;data:Record<string,unknown>;created_at:string}
export interface Integrations {razorpay:{configured:boolean;mode:string;key_id_masked:string|null;last_verified_webhook_at:string|null};smtp:{configured:boolean;sender:string|null};ollama:{configured:boolean;model:string;embedding_model:string}}
export interface Intelligence {agent:{backend:string;model:string;configured:boolean;recommendations:number};embeddings:{model:string;indexed_documents:number;status:string};recovery_model:{artifact_present:boolean;status:string}}
export type HealthStatus='HEALTHY'|'DOWN'|'NOT_CONFIGURED'|'NOT_EXPOSED'|'CONFIGURED'; export interface DetailedHealth {api:{status:HealthStatus};postgresql:{status:HealthStatus;latency_ms?:number};redis:{status:HealthStatus};celery:{status:HealthStatus};razorpay:{status:HealthStatus};smtp:{status:HealthStatus};ollama:{status:HealthStatus;latency_ms?:number};qwen:{status:HealthStatus};embeddings:{status:HealthStatus}}
