'use client';
import {useQuery} from '@tanstack/react-query';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {recoverosApi} from '@/lib/api/recoveros'; import {queryKeys} from '@/lib/query/keys';
import {EmptyState,ErrorState,LoadingState} from '@/components/shared/states'; import {MoneyValue,StatusBadge} from '@/components/shared/ui';
export default function Overview(){
  const query=useQuery({queryKey:queryKeys.overview,queryFn:recoverosApi.overview});
  if(query.isLoading)return <main className="page"><LoadingState/></main>;
  if(query.isError||!query.data)return <main className="page"><ErrorState/></main>;
  const d=query.data;
  const cards:[string,React.ReactNode,string,string][]=[['Revenue at Risk',<MoneyValue minor={d.revenue_at_risk_minor}/>, 'Open provider-backed exposure','emphasis-risk'],['Recovered Revenue',<MoneyValue minor={d.revenue_recovered_minor}/>, 'Verified and attributed only','emphasis-recovered'],['Open Recovery Cases',d.open_cases,'Awaiting an outcome',''],['Recovery Rate',`${d.recovery_rate}%`,'Conservative attribution',''],['Needs Human Review',d.human_escalations,'Policy-led review queue','emphasis-review']];
  return <main className="page"><header className="page-head"><div><div className="eyebrow">Executive overview</div><h1 className="page-title">Revenue recovery operations</h1><p className="page-subtitle">Payment facts, intelligence, policy, and verified outcomes in one operational view.</p></div><span className="mode">TEST MODE · NO REAL MONEY</span></header>{!d.total_cases?<div className="card"><EmptyState title="No payment events have been ingested yet" description="Connect Razorpay Test Mode and generate a signed payment event to start recovery analysis."/></div>:<><section className="grid-metrics">{cards.map(([label,value,note,style])=><div className={`card metric-card ${style}`} key={label}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>)}</section><section className="two-col"><div className="card"><div className="card-head"><h2 className="card-title">Revenue at risk vs. recovered</h2><p className="card-subtitle">Observed values from persisted provider events—never projections.</p></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={d.trend}><defs><linearGradient id="risk" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#dc2626" stopOpacity=".2"/><stop offset="1" stopColor="#dc2626" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={v=>`₹${Number(v)/100}`}/><Tooltip formatter={(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(v/100)}/><Area type="monotone" dataKey="risk" name="Revenue at risk" stroke="#dc2626" fill="url(#risk)" strokeWidth={2}/><Area type="monotone" dataKey="recovered" name="Recovered revenue" stroke="#059669" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="card"><div className="card-head"><h2 className="card-title">Safety ledger</h2><p className="card-subtitle">Controls calculated from persisted workflow activity.</p></div><div className="card-body">{[['Unauthorized money actions',d.safety.unauthorized_money_actions],['Duplicate actions prevented',d.safety.duplicate_actions_prevented],['Disputed customers contacted',d.safety.disputed_customers_contacted],['Policy blocks',d.policy_blocks]].map(([label,value])=><div className="rule" key={label}><span>{label}</span><StatusBadge value={Number(value)===0?'CLEAR':String(value)}/></div>)}</div></div></section></>}</main>
}
