from enum import StrEnum


class CaseType(StrEnum):
    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    PAYMENT_DEGRADATION = "PAYMENT_DEGRADATION"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    OVERDUE_RECEIVABLE = "OVERDUE_RECEIVABLE"
    PAYMENT_LINK_UNPAID = "PAYMENT_LINK_UNPAID"
    PROMISE_TO_PAY_BROKEN = "PROMISE_TO_PAY_BROKEN"


class CaseState(StrEnum):
    DETECTED = "DETECTED"
    DIAGNOSING = "DIAGNOSING"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    AUTHORIZED = "AUTHORIZED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    WAITING_FOR_OUTCOME = "WAITING_FOR_OUTCOME"
    NEXT_ACTION_DUE = "NEXT_ACTION_DUE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    CLOSED = "CLOSED"


class FailureCategory(StrEnum):
    AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE"
    TRANSIENT_PROVIDER_FAILURE = "TRANSIENT_PROVIDER_FAILURE"
    CUSTOMER_ACTION_REQUIRED = "CUSTOMER_ACTION_REQUIRED"
    PAYMENT_METHOD_FAILURE = "PAYMENT_METHOD_FAILURE"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    EXPIRED_PAYMENT_REQUEST = "EXPIRED_PAYMENT_REQUEST"
    REPEATED_FAILURE = "REPEATED_FAILURE"
    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"
    DATA_INCONSISTENCY = "DATA_INCONSISTENCY"


class RecoveryAction(StrEnum):
    NO_ACTION = "NO_ACTION"
    WAIT = "WAIT"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    SEND_RECOVERY_MESSAGE = "SEND_RECOVERY_MESSAGE"
    SUGGEST_ALTERNATE_METHOD = "SUGGEST_ALTERNATE_METHOD"
    RECORD_PROMISE_TO_PAY = "RECORD_PROMISE_TO_PAY"
    SCHEDULE_FOLLOWUP = "SCHEDULE_FOLLOWUP"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"


class PolicyResolution(StrEnum):
    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"


class AuditEventType(StrEnum):
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_VERIFIED = "WEBHOOK_VERIFIED"
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    DIAGNOSIS_CREATED = "DIAGNOSIS_CREATED"
    AGENT_RECOMMENDATION_CREATED = "AGENT_RECOMMENDATION_CREATED"
    POLICY_ALLOWED = "POLICY_ALLOWED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    HUMAN_APPROVAL_REQUESTED = "HUMAN_APPROVAL_REQUESTED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"
    MESSAGE_SENT = "MESSAGE_SENT"
    PAYMENT_LINK_CREATED = "PAYMENT_LINK_CREATED"
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    CASE_RECOVERED = "CASE_RECOVERED"
    CASE_ESCALATED = "CASE_ESCALATED"
    ACTION_CANCELLED_ALREADY_PAID = "ACTION_CANCELLED_ALREADY_PAID"
